apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: app
  labels:
    app: redis
    tier: backend
    role: master
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: master