# run locally with: ansible-playbook create_playbook.yml --connection=local

---
- hosts: 127.0.0.1
  become: no
  vars:
    playbook_name: ansibleskeleton
    location: /tmp/{{ playbook_name }}
    roles: ["web", "database", "common"]


  tasks:
    - name: Check if the playbook already exists
      stat: path={{ location }}
      register: playbook_directory

    - name: Create playbook directory
      file: path={{ item }} state=directory
      when: playbook_directory.stat.exists == False
      with_items:
        - "{{ location }}"
        - "{{ location }}/group_vars"
        - "{{ location }}/roles"

    - name: Create playbook files
      file: path={{ item }} state=touch
      with_items:
        - "{{ location }}/group_vars/all"
        - "{{ location }}/{{ playbook_name }}.yml"

    - name: Create role + task directories
      file: path={{ location }}/roles/{{ item }}/tasks state=directory mode=0755
      with_items: "{{ roles }}"

    - name: Create handler directory for each role
      file: path={{ location }}/roles/{{ item }}/handlers state=directory mode=0755
      with_items: "{{ roles }}"

    - name: Create templates directory for each role
      file: path={{ location }}/roles/{{ item }}/templates state=directory mode=0755
      with_items: "{{ roles }}"

    - name: Create files directory for each role
      file: path={{ location }}/roles/{{ item }}/files state=directory mode=0755
      with_items: "{{ roles }}"

    - name: Create vars directory for each role
      file: path={{ location }}/roles/{{ item }}/vars state=directory mode=0755
      with_items: "{{ roles }}"

    - name: Create meta directory for each role
      file: path={{ location }}/roles/{{ item }}/meta state=directory mode=0755
      with_items: "{{ roles }}"

    - name: Create task file for each role
      file: path={{ location }}/roles/{{ item }}/tasks/main.yml state=touch
      with_items: "{{ roles }}"

    - name: Create handler file for each role
      file: path={{ location }}/roles/{{ item }}/handlers/main.yml state=touch
      with_items: "{{ roles }}"

