apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: app-dev
  labels:
    app: redis
    tier: backend
    role: slave
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
    tier: backend
    role: slave