apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slave-pvc
  namespace: app-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem