# Go over the tags as well and make sure your cluster name is used in each one

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: john # same as the cluster name in subnet tags
  region: us-east-1
  version: "1.16"

vpc:
  subnets:
    public:
      us-east-1b: { id: subnet-07e2ba8a2f2c9bc04 }
      us-east-1c: { id: subnet-0a5c0b37a9327995c }
    private:
      us-east-1a: { id: subnet-05f957e014ba79f10 }
      us-east-1b: { id: subnet-07f7408b67f545cf2 }


nodeGroups:
  - name: sample-asg-1
    #clusterDNS: 169.254.20.10
    minSize: 1
    maxSize: 200
    desiredCapacity: 1
    instancesDistribution:
      instanceTypes: ["t2.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
    labels:
      lifecycle: Ec2Spot
      app: guestbook
      nodegroup-name: guestbook
    taints:
      app: "guestbook:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/app: guestbook
      k8s.io/cluster-autoscaler/node-template/taint/special: "true:NoSchedule"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/john: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      publicKeyName: eks-worker
  - name: sample-asg-2
    #clusterDNS: 169.254.20.10
    minSize: 1
    maxSize: 200
    desiredCapacity: 1
    instancesDistribution:
      instanceTypes: ["t2.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: "capacity-optimized"
    labels:
      lifecycle: Ec2Spot
      app: redis-slave
      nodegroup-name: redis-slave
    taints:
      app: "redisslave:NoSchedule"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/lifecycle: Ec2Spot
      k8s.io/cluster-autoscaler/node-template/label/app: redisslave
      k8s.io/cluster-autoscaler/node-template/taint/special: "true:NoSchedule"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/john: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true
    ssh:
      publicKeyName: eks-worker
managedNodeGroups:
  - name: sample-managed-nodegroup-1
    #clusterDNS: 169.254.20.10
    instanceType: t2.small
    minSize: 1
    maxSize: 100
    desiredCapacity: 3
    volumeSize: 50
    ssh:
      publicKeyName: eks-worker
    labels:
      nodegroup-name: on-demand-4-16
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/john: "owned"
    iam:
      withAddonPolicies:
        autoScaler: true