kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: promtheus-ssd
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: prometheus-operator-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
  volumeMode: Filesystem
