kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage-ssd
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
