apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: first-comp
  namespace: crossplane-system
spec:
  compositeTypeRef:
    apiVersion: example.org/v1alpha1
    kind: xMyBuckets
  resources:
    - name: StorageBucket-1
      base:
        apiVersion: storage.gcp.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: my-bucket-1
        spec:
          providerConfigRef:
            name: gcp-provider-config
          forProvider:
            location: US
    - name: StorageBucket-2
      base:
        apiVersion: storage.gcp.upbound.io/v1beta1
        kind: Bucket
        # metadata:
        #   name: my-bucket-2
        spec:
          providerConfigRef:
            name: gcp-provider-config
          forProvider:
            location: US
     
      